"""
Discrete-event simulator for a non-stationary Mt/M/c/c loss queue with a
time-varying arrival rate lambda(t). Arrivals are generated by thinning a
homogeneous Poisson process at the peak rate; an arrival that finds all c servers
busy is blocked. Reports the blocking probability as a function of the phase over
a periodic cycle — the ground truth for the PSA/MOL approximations.
"""

import heapq

from most_queue.sim.base_core import BaseSimulationCore


class TimeVaryingMMcSim(BaseSimulationCore):
    """
    :param n: number of servers c.
    :param period: length of one cycle of lambda(t) (for phase bucketing).
    :param n_buckets: number of phase buckets across the cycle.
    :param seed: RNG seed.
    """

    def __init__(self, n: int, period: float, n_buckets: int = 40, seed: int | None = None):
        super().__init__(seed=seed)
        self.c = n
        self.period = period
        self.nb = n_buckets
        self.lam_fn = None
        self.lam_max = None
        self.mu = None

    def set_sources(self, lam_fn, lam_max: float):
        """:param lam_fn: callable t -> lambda(t). :param lam_max: an upper bound on lambda(t)."""
        self.lam_fn = lam_fn
        self.lam_max = lam_max

    def set_servers(self, mu: float):
        """:param mu: per-server service rate."""
        self.mu = mu

    def run(self, horizon: float, warmup_fraction: float = 0.05):
        """Run to time `horizon`; return per-phase blocking probability arrays (t_centers, prob)."""
        if self.lam_fn is None or self.mu is None:
            raise RuntimeError("set sources and servers before run()")
        rng = self.generator
        c, nb, period = self.c, self.nb, self.period
        busy = 0
        dep: list = []  # heap of departure times
        blocked = [0.0] * nb
        total = [0.0] * nb
        t = 0.0
        warm = horizon * warmup_fraction
        while t < horizon:
            t += rng.exponential(1.0 / self.lam_max)
            while dep and dep[0] <= t:
                heapq.heappop(dep)
                busy -= 1
            if rng.random() < self.lam_fn(t) / self.lam_max:  # accept (thinning)
                full = busy >= c
                if t > warm:
                    ph = int((t % period) / period * nb) % nb
                    total[ph] += 1
                    if full:
                        blocked[ph] += 1
                if not full:  # loss system: an arrival to a full system is dropped
                    busy += 1
                    heapq.heappush(dep, t + rng.exponential(1.0 / self.mu))
        t_centers = [(i + 0.5) / nb * period for i in range(nb)]
        prob = [blocked[i] / total[i] if total[i] else 0.0 for i in range(nb)]
        return t_centers, prob
